name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2.3.0
      with:
        python-version: 3.9
    - name: Set up Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install -E db --no-interaction
    - name: Check version
      run: |
        [ "$(poetry run python -c 'import acnutils; print(acnutils.__version__)')" == "$(poetry version -s)" ]
    - name: Static type check with mypy
      run :
        poetry run mypy acnutils
    - name: Test with pytest
      run: |
        poetry run python -m pytest
    - name: Build package
      run: poetry build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
    - name: Publish package
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
      run: poetry publish
